services:
  - mongodb
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - npm run coveralls